### ISSUE TITLE
Great work. This worked a year ago but now getting an issue I can't solve regarding attribute 'keys'

### ISSUE THREAD

**Issue by Drew2019** [equialgo/fairness-in-ml#11]
This is a great application. 

I played around with this some for a custom application, and last year it worked well. However, when I tried to run it yesterday (pretraining and fitting) I experienced an error I'm having a hard time correcting. Any idea how to solve:

AttributeError: 'list' object has no attribute 'keys'

I assume it has to do with the class weights but am having challenges correcting.

**Comment by equialgo** [comment]
I updated the notebook of the original blog post to make it compatible with TF 2.0. Also fixing some more compatibility issues. This will probably also resolve the issues you are encountering. Could you check this?

**Comment by equialgo** [comment]
The updates the code base should have resolved the issues. I am closing this issue.
