### ISSUE TITLE
How could I achieve the animation graph? Thanks

### ISSUE THREAD

**Issue by Bee-zest** [equialgo/fairness-in-ml#5]

**Comment by hgrif** [comment]
Hi @Bee-zest,

The animation is generated by saving matplotlib figures as png images and converting them to a gif with the command (see the last code cell of [this Notebook](https://github.com/equialgo/fairness-in-ml/blob/master/fairness-in-ml.ipynb):

`convert -loop 0 -delay 0 output/*.png -delay 500 output/00000165.png images/training.gif`

I believe `convert` is a tool from [imagemagick](https://linux.die.net/man/1/convert). Alternatively, you could look into `matplotlib.animation` (see an example [here](https://eli.thegreenplace.net/2016/drawing-animated-gifs-with-matplotlib/)).


Good luck!

**Comment by Bee-zest** [comment]
Thank you so much

Henk Griffioen <notifications@github.com>于2019年3月13日 周三上午5:36写道：
