### ISSUE TITLE
Serialize fair classifier

### ISSUE THREAD

**Issue by dlmracek** [equialgo/fairness-in-ml#6]
Nice work, thanks for sharing. Do you have a recommendation for serializing _trainable_clf_net to the exclusion of _trainable_adv_net.

For example, 

from keras.models import load_model
_trainable_clf_net.save('fair_model.h5')

**Comment by equialgo** [comment]
Hi @dlmracek, sorry but I cannot give you further advise on this one. Besides that I would recommend to use this code/solution for inspiration only. For real applications, I would advise to rebuild the whole thing in Tensorflow 2.x!
